### ISSUE TITLE
Publish to LuaRocks

### ISSUE THREAD

**Issue by meme** [launchdarkly/lua-server-sdk#16]
As there are now 1.0 releases, please consider publishing to LuaRocks directly. It seems that LaunchDarkly already has a LuaRocks account: https://luarocks.org/modules/launchdarkly.

**Comment by hroederld** [comment]
Hi @meme 

We will look more into uploading a package to LuaRocks, especially now that someone is requesting it. We have not done so already mainly because the SDK has a few native dependencies that makes it slightly less valuable. In that you still have to install libpcre, libcurl, and libldserversdk outside of luarocks. We originally created the account to reserve the name for publishing later.

**Comment by meme** [comment]
There are many other modules on LuaRocks which also require shared libraries to be present on the system, so I do not believe that is an unreasonable request for an end-user. This would still greatly simplify setting up/updating an environment :+1:

**Comment by cwaldren-ld** [comment]
Hi @meme, thank you for your patience. I agree it is a reasonable request. I will discuss with the team internally. 

_Filed internally as 141289._

**Comment by frankgreco** [comment]
Is there an update on this? I was going to open an issue for this exact issue! Love this project btw!

**Comment by cwaldren-ld** [comment]
Hi @frankgreco , no update yet.

We're currently in the process of updating this SDK to build against our [C++ Server-side SDK](https://github.com/launchdarkly/cpp-sdks), as well as overhauling the release process, which will make furthur changes significantly easier.

I don't have a timeline for LuaRocks but it is on our backlog.

**Comment by cwaldren-ld** [comment]
Hi all, the SDK and its Redis integration are now published to LuaRocks: https://luarocks.org/modules/launchdarkly

As mentioned in the comments above, since the SDK depends on the native C++ SDK, it must first be installed on the host before the Lua binding will work.

Please, don't hesitate to let us know if you have any feedback.
