### ISSUE TITLE
Support for Lua 5.3

### ISSUE THREAD

**Issue by puffnfresh** [launchdarkly/lua-server-sdk#9]
We're trying to incorporate feature flagging in our HAProxy instance.

I built this library for HAProxy and got it running but it would segfault. I then noticed:

> Lua 5.3 is not supported due to FFI constraints.

Sadly this is blocking us since HAProxy says:

> Only versions 5.3 and above are supported.

What's the feasibility of getting this ported to Lua 5.3 so that we can use this for HAProxy?

**Comment by hroederld** [comment]
Hello @puffnfresh 

We will start working on that next week, and hopefully get a new release out.

Thanks!

**Comment by puffnfresh** [comment]
@hroederld for now I've unblocked myself by writing a tiny C binding just for the function we need:

https://gist.github.com/puffnfresh/91e162556723ec0885e3d01c52b152bd

This is working pretty well for our HAProxy configuration:

```lua
local ld = require("launchdarkly")

core.register_fetches("flag_is_enabled", function(txn, key)
  return ld.isEnabled(key, "example")
end)
```

And in HAProxy config:

```
http-request deny if { lua.flag_is_enabled("deny-requests") -m bool }
```

Unless you see any significant issues with this, I don't think we need any more features than this.

**Comment by hroederld** [comment]
We put out a Beta 3 release today that supports Lua 5.3, 5.2, 5.1, and luajit. There is some basic CI to validate the build on each version. we will tryout 5.4 later. Although our larger integration tests are still only against 5.1.

Supporting them ended up being a substantial change. The `ffi` package does not play nicely with other versions. so it was all rewritten as a C shim. See the updated hello app if you want to try it out `https://github.com/launchdarkly/hello-lua-server`. The websites doc is not yet updated but will be soon.

Because the SDK is not yet GA, and because these changes were substantial I recommended not using the new Beta 3 in production yet though. This week we are writing a demo app for HAProxy similar to https://github.com/launchdarkly/hello-nginx (which has not been updated to Beta 3 yet) and we can make sure everything plays nicely together.

Thanks!

**Comment by hroederld** [comment]
Hi @puffnfresh 

We put out a little proof of concept validating that the new version works in HAProxy: https://github.com/launchdarkly/hello-haproxy/

We will have a GA in the near future. I am going to close this issue for now as I think the recent changes should have resolved your problems.
